site_name: Odoo Docs
site_description: Documentação do Odoo

nav:
  - Guia: index.md  
  - Instalação: install/index.md
  - Implatação: index  
  - Testes: install/index.md
  - Sobre: about

theme: 
  name: readthedocs
  locale: pt_BR

extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  
plugins:
  - search
  - mermaid2
  